=== SecTedd/PSEMolDyn_GroupG/src/xsd/SimulationState.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="simulation_state_t">
        <xs:sequence>
            <xs:element name="particle" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mass" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="epsilon" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="sigma" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="type" type="xs:int" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="stiffness" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="averageBondLength" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="x">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="v">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="f">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="old_f">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="simulation_state" type="simulation_state_t"/>
</xs:schema>

=== SecTedd/PSEMolDyn_GroupG/input/SimulationState.xml
<?xml version="1.0"?>
<simulation_state xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../src/xsd/SimulationState.xsd">
    <particle>
        <mass>1</mass>
        <epsilon>1</epsilon>
        <sigma>1</sigma>
        <type>1</type>
        <stiffness>1</stiffness>
        <averageBondLength>1</averageBondLength>
        <x>
            <x>1</x>

            <y>1</y>

            <z>0</z>
        </x>
        <v>
            <x>1</x>

            <y>1</y>

            <z>1</z>
        </v>
        <f>
            <x>1</x>

            <y>1</y>

            <z>1</z>
        </f>
        <old_f>
            <x>1</x>

            <y>1</y>

            <z>1</z>
        </old_f>
    </particle>

</simulation_state>
