=== SecTedd/PSEMolDyn_GroupG/src/xsd/Simulation.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="simulation_t">
        <xs:sequence>
            <xs:element name="end_time" type="xs:double" maxOccurs="1" minOccurs="1"/>
            <xs:element name="delta_t" type="xs:double" maxOccurs="1" minOccurs="1"/>
            <xs:element name="sigma" type="xs:double" maxOccurs="1" minOccurs="1"/>
            <xs:element name="epsilon" type="xs:double" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cutoff" type="xs:double" maxOccurs="1" minOccurs="1"/>
            <xs:element name="file_name" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="domain">
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="d1" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="d2" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="d3" type="xs:double" maxOccurs="1" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cuboid" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mass" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="h" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="meanV" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="type" type="xs:int" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="position">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="velocity">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="dimensions">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:int" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:int" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:int" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sphere" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mass" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="h" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="meanV" type="xs:double" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="type" type="xs:int" maxOccurs="1" minOccurs="1"/>
                        <xs:element name="r" type="xs:int" maxOccurs="1" minOccurs="1"/>                            
                        <xs:element name="center">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="velocity">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="x" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="y" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                    <xs:element name="z" type="xs:double" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="simulation" type="simulation_t"/>
</xs:schema>

=== SecTedd/PSEMolDyn_GroupG/input/Simulation1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <end_time>10</end_time>
    <delta_t>0.00005</delta_t>
    <sigma>1</sigma> 
    <epsilon>5</epsilon>
    <cutoff>3.0</cutoff>
    <file_name>eingabe-sphere.txt</file_name>
    <domain>
        <d1>120</d1>
        <d2>50</d2>
        <d3>1</d3>
    </domain>
</simulation>

=== SecTedd/PSEMolDyn_GroupG/input/Simulation2.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/xsd/Simulation.xsd">
    <end_time>0.0005</end_time>
    <delta_t>0.00005</delta_t>
    <sigma>1</sigma> 
    <epsilon>5</epsilon>
    <cutoff>3.0</cutoff>
    <domain>
        <x>150</x>
        <y>80</y>
        <z>0</z>
    </domain>
    <boundaries>
        <xLeft>Reflecting</xLeft>
        <xRight>Reflecting</xRight>
        <yBottom>Reflecting</yBottom>
        <yTop>Reflecting</yTop>
        <zFront>Reflecting</zFront>
        <zBack>Reflecting</zBack>
    </boundaries>
    <writeFrequency>10</writeFrequency>
    <baseName>outputVTK/</baseName>
    <cuboid>
        <mass>1.0</mass>
        <h>1.1225</h>
        <meanV>0.1</meanV>
        <type>1</type>
        <position>
            <x>20</x>
            <y>20</y>
            <z>0</z>
        </position>
        <velocity>
            <x>0</x>
            <y>0</y>
            <z>0</z>
        </velocity>
        <dimensions>
            <x>100</x>
            <y>20</y>
            <z>1</z>
        </dimensions>
    </cuboid>
    <sphere>
        <mass>1.0</mass>
        <h>1.1225</h>
        <meanV>0.1</meanV>
        <type>1</type>
        <r>15</r>
        <center>
            <x>25</x>
            <y>20</y>
            <z>0</z>
        </center>
        <velocity>
            <x>0</x>
            <y>0</y>
            <z>0</z>
        </velocity>
    </sphere>
</simulation>
